export class NutritionPlan {
  public readonly startDate: Date;
  public readonly startWeightKg: number;
  public readonly targetWeightKg: number;
  public readonly targetDate: Date;
  public readonly bmr: number;
  public readonly tdee: number;
  public readonly estimatedTdee: number;
  public readonly actualTdee: number | null;
  public readonly actualTdeeCalculatedAt: Date | null;
  public readonly actualTdeeWindowDays: number | null;
  public readonly dailyBaseBurnKcal: number;
  public readonly dailyActivityBurnKcal: number;
  public readonly dailyTotalBurnKcal: number;
  public readonly dailyEnergyAdjustmentKcal: number;
  public readonly targetCalories: number;
  public readonly proteinG: number;
  public readonly carbsG: number;
  public readonly fatG: number;
  public readonly totalFatG: number;
  public readonly fiberG: number;
  public readonly waterMl: number;
  public readonly saturatedFatLimitG: number;
  public readonly omega3TargetG: number;
  public readonly transFatLimitG: number;
  public readonly macroRatio: string;
  public readonly calculatedAt: Date;

  constructor(data: {
    startDate: Date;
    startWeightKg: number;
    targetWeightKg: number;
    targetDate: Date;
    bmr: number;
    tdee: number;
    estimatedTdee: number;
    actualTdee: number | null;
    actualTdeeCalculatedAt: Date | null;
    actualTdeeWindowDays: number | null;
    dailyBaseBurnKcal: number;
    dailyActivityBurnKcal: number;
    dailyTotalBurnKcal: number;
    dailyEnergyAdjustmentKcal: number;
    targetCalories: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
    totalFatG: number;
    fiberG: number;
    waterMl: number;
    saturatedFatLimitG: number;
    omega3TargetG: number;
    transFatLimitG: number;
    macroRatio: string;
    calculatedAt: Date;
  }) {
    this.startDate = data.startDate;
    this.startWeightKg = data.startWeightKg;
    this.targetWeightKg = data.targetWeightKg;
    this.targetDate = data.targetDate;
    this.bmr = data.bmr;
    this.tdee = data.tdee;
    this.estimatedTdee = data.estimatedTdee;
    this.actualTdee = data.actualTdee;
    this.actualTdeeCalculatedAt = data.actualTdeeCalculatedAt;
    this.actualTdeeWindowDays = data.actualTdeeWindowDays;
    this.dailyBaseBurnKcal = data.dailyBaseBurnKcal;
    this.dailyActivityBurnKcal = data.dailyActivityBurnKcal;
    this.dailyTotalBurnKcal = data.dailyTotalBurnKcal;
    this.dailyEnergyAdjustmentKcal = data.dailyEnergyAdjustmentKcal;
    this.targetCalories = data.targetCalories;
    this.proteinG = data.proteinG;
    this.carbsG = data.carbsG;
    this.fatG = data.fatG;
    this.totalFatG = data.totalFatG;
    this.fiberG = data.fiberG;
    this.waterMl = data.waterMl;
    this.saturatedFatLimitG = data.saturatedFatLimitG;
    this.omega3TargetG = data.omega3TargetG;
    this.transFatLimitG = data.transFatLimitG;
    this.macroRatio = data.macroRatio;
    this.calculatedAt = data.calculatedAt;
  }
}
