-- AlterTable
ALTER TABLE "DailyRecord" ADD COLUMN     "waterMl" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "FoodItem" ADD COLUMN     "fiberPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "omega3Per100g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saturatedFatPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalFatPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transFatPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "MealEntry" ADD COLUMN     "fiberG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "omega3G" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saturatedFatG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalFatG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transFatG" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "NutritionTarget" ADD COLUMN     "dailyActivityBurnKcal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "dailyBaseBurnKcal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "dailyEnergyAdjustmentKcal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "dailyTotalBurnKcal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fiberG" DOUBLE PRECISION NOT NULL DEFAULT 25,
ADD COLUMN     "omega3TargetG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saturatedFatLimitG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "startWeightKg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "targetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "targetWeightKg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalFatG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transFatLimitG" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "waterMl" DOUBLE PRECISION NOT NULL DEFAULT 0;
